In [2]:
import numpy as np

In [3]:
matrix1=np.matrix([[1,2,3],[4,5,6],[7,8,9]])
a1=matrix1
print(matrix1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [4]:
matrix2=np.matrix([[10,20,30],[40,50,60],[70,80,90]])
a2=matrix2
print(matrix2)

[[10 20 30]
 [40 50 60]
 [70 80 90]]


In [5]:
matrix_multiplication=a1*a2
print(matrix_multiplication)

[[ 300  360  420]
 [ 660  810  960]
 [1020 1260 1500]]


In [6]:
transpose_a1=np.transpose(a1)
print(transpose_a1)

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [7]:
invers=np.linalg.inv(a2)
print(invers)

[[ 1.97032484e+15 -3.94064967e+15  1.97032484e+15]
 [-3.94064967e+15  7.88129935e+15 -3.94064967e+15]
 [ 1.97032484e+15 -3.94064967e+15  1.97032484e+15]]


In [8]:
det=np.linalg.det(a1)
print(det)

-9.51619735392994e-16
