In [2]:
import numpy as np

In [3]:
arr1_1d=np.array([1,2,3,4,5])
arr2_1d=np.array([10,20,30,40,50])
arr2_1d

array([10, 20, 30, 40, 50])

In [4]:
arr1_2d=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
arr2_2d=np.array([[10,20,30],[40,50,60],[70,80,90],[100,110,120]])
for i in arr2_2d:
    for j in i:
        print(j,end=" ")

10 20 30 40 50 60 70 80 90 100 110 120 

In [5]:
arr1_3d=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
arr2_3d=np.array([[[10,20,30],[40,50,60]],[[70,80,90],[100,110,120]]])
for i in arr2_3d:
    for k in i:
        for j in k:
            print(j,end=" ")
    print()

10 20 30 40 50 60 
70 80 90 100 110 120 


In [6]:
add_1d=np.add(arr1_1d,arr2_1d)
add_1d

array([11, 22, 33, 44, 55])

In [7]:
subtract_1d=np.subtract(arr1_1d,arr2_1d)
subtract_1d

array([ -9, -18, -27, -36, -45])

In [8]:
divide_1d=np.divide(arr2_1d,arr1_1d)
divide_1d

array([10., 10., 10., 10., 10.])

In [9]:
multiply_1d=np.multiply(arr2_1d,arr1_1d)
multiply_1d

array([ 10,  40,  90, 160, 250])

In [10]:
mod_1d=np.mod(arr1_1d,arr2_1d)
mod_1d

array([1, 2, 3, 4, 5])

In [11]:
power_1d=np.power(arr2_1d,arr1_1d)
power_1d

array([       10,       400,     27000,   2560000, 312500000])

In [12]:
min_1d=np.min(arr2_1d)
min_1d

10

In [13]:
max_1d=np.max(arr2_1d)
max_1d

50

In [14]:
argmin_1d=np.argmin(arr2_1d)
argmin_1d

0

In [15]:
argmax_1d=np.argmax(arr2_1d)
argmax_1d

4

In [16]:
# sin

In [17]:
# cos

In [18]:
# sqrt

In [19]:
# comsum 

In [20]:
concatenate_1d=np.concatenate((arr1_1d,arr2_1d))
concatenate_1d

array([ 1,  2,  3,  4,  5, 10, 20, 30, 40, 50])

In [21]:
concatenate_2d_axis0=np.concatenate((arr1_2d,arr2_2d),axis=0)
concatenate_2d_axis0

array([[  1,   2,   3],
       [  4,   5,   6],
       [  7,   8,   9],
       [ 10,  11,  12],
       [ 10,  20,  30],
       [ 40,  50,  60],
       [ 70,  80,  90],
       [100, 110, 120]])

In [22]:
concatenate_2d_axis1=np.concatenate((arr1_2d,arr2_2d),axis=1)
concatenate_2d_axis1

array([[  1,   2,   3,  10,  20,  30],
       [  4,   5,   6,  40,  50,  60],
       [  7,   8,   9,  70,  80,  90],
       [ 10,  11,  12, 100, 110, 120]])

In [23]:
split_1d=np.array_split(arr2_1d,2)
split_1d

[array([10, 20, 30]), array([40, 50])]

In [24]:
reciprocal_3d=np.reciprocal(arr2_3d)
reciprocal_3d

array([[[0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0]]])